/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Minh Tri
 */
import Model.HienThi;
import static Model.LayNghia.LayNghiaTu;
import Model.NapTu;
import Model.Speak;
import Model.URLHinhAnh;
import Model.HienThi;
import java.io.*;
import com.sun.speech.freetts.*;
import java.awt.Image;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
public class Frame_Dic extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Dic
     */
    
    private static Vector listWord = new Vector();
    private static Vector dataWordEnglish_translated = new Vector();
    private static Vector dataWordViet_translated = new Vector();
    private static Vector wordlistEnglish_translated = new Vector();
    private static Vector wordlistViet_translated = new Vector();
    public Frame_Dic() {
        initComponents();
        ImageIcon SoundIcon = new ImageIcon("sound_icon.png");
        Image img_icon = SoundIcon.getImage(); 
        Image newimg = img_icon.getScaledInstance(23, 23,  java.awt.Image.SCALE_SMOOTH);
        SoundIcon = new ImageIcon(newimg); 
        btnSound.setIcon(SoundIcon);
        
        ImageIcon SearchIcon = new ImageIcon("search_icon.png");
        Image img_search = SearchIcon.getImage(); 
        Image newSearch = img_search.getScaledInstance(25, 25,  java.awt.Image.SCALE_SMOOTH);
        SearchIcon = new ImageIcon(newSearch); 
        btnSearch.setIcon(SearchIcon);
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        radioGroup = new javax.swing.ButtonGroup();
        rdAnhViet = new javax.swing.JRadioButton();
        rdVietAnh = new javax.swing.JRadioButton();
        label1 = new java.awt.Label();
        txt_search = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnSound = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMeaning = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        list_Word = new javax.swing.JList<>();
        jHinhAnh = new javax.swing.JLabel();
        btnThongTin = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dictionary E - V / V - E");
        setResizable(false);

        radioGroup.add(rdAnhViet);
        rdAnhViet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdAnhViet.setText("English - Vietnamese");
        rdAnhViet.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        radioGroup.add(rdVietAnh);
        rdVietAnh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdVietAnh.setText("Vietnamese - English");

        label1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label1.setText("SEARCH:");

        txt_search.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(0, 255, 0));
        btnSearch.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        btnSound.setBackground(new java.awt.Color(51, 255, 255));
        btnSound.setText("Speak");
        btnSound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoundActionPerformed(evt);
            }
        });

        txtMeaning.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jScrollPane3.setViewportView(txtMeaning);

        list_Word.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        list_Word.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list_Word.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                list_WordKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(list_Word);

        btnThongTin.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnThongTin.setText("About Author");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSearch)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnSound))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnThongTin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdAnhViet)
                        .addGap(39, 39, 39)
                        .addComponent(rdVietAnh)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rdAnhViet)
                    .addComponent(rdVietAnh))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSound, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(btnThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    private void btnSoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoundActionPerformed

           Speak.read(txt_search.getText());
    }//GEN-LAST:event_btnSoundActionPerformed

    
    
    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
        HienThi ht = new HienThi(txt_search, rdAnhViet, rdVietAnh, txtMeaning, list_Word, jHinhAnh, dataWordEnglish_translated, dataWordViet_translated, wordlistEnglish_translated, wordlistViet_translated);                      
    }//GEN-LAST:event_btnSearchMouseClicked

    private void list_WordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_list_WordKeyPressed
        // TODO add your handling code here:
        int indexSelected = list_Word.getSelectedIndex();
        String wordSelected = list_Word.getSelectedValue();
        txt_search.setText(wordSelected);
        try {
            URLHinhAnh.LayLink(wordSelected, jHinhAnh);
        } catch (IOException ex) {
            Logger.getLogger(Frame_Dic.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(rdAnhViet.isSelected())
        {
            String dataWordSelected = (String)dataWordEnglish_translated.get(indexSelected);
            
            txtMeaning.setText(dataWordSelected);
            txtMeaning.setCaretPosition(0);
            
        }
        if(rdVietAnh.isSelected())
        {
            String dataWordSelected = (String)dataWordViet_translated.get(indexSelected);
            
            txtMeaning.setText(dataWordSelected);
            txtMeaning.setCaretPosition(0);
        }
    }//GEN-LAST:event_list_WordKeyPressed

    private void txt_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n')
        {
            //HienThi(txt_search, rdAnhViet, rdVietAnh, txtMeaning, list_Word, jHinhAnh);
             HienThi ht = new HienThi(txt_search, rdAnhViet, rdVietAnh, txtMeaning, list_Word, jHinhAnh, dataWordEnglish_translated, dataWordViet_translated, wordlistEnglish_translated, wordlistViet_translated);
        }
    }//GEN-LAST:event_txt_searchKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Dic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Dic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Dic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Dic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Dic().setVisible(true);                           
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSound;
    private javax.swing.JButton btnThongTin;
    private javax.swing.JLabel jHinhAnh;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private java.awt.Label label1;
    private javax.swing.JList<String> list_Word;
    private javax.swing.ButtonGroup radioGroup;
    private javax.swing.JRadioButton rdAnhViet;
    private javax.swing.JRadioButton rdVietAnh;
    private javax.swing.JTextPane txtMeaning;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
